baseURL: https://www.provadigital.com.br/
languageCode: en-us
title: Charles Santos
theme: bash

Params:
  description: |
    Charles Henrique Gonçalves Santos, graduado em Engenharia de Computação, mestre em Sistemas Mecatrônicos e doutorando em informática. 
    Atualmente atuo como Analista de Infraestrutura no Ministério Público do Trabalho (MPT.mp.br), 
    sendo o líder do time DevOps, dado a minha excelência em Linux e Kubernetes comprovada pelas certificações 
    profissionais internacionais CKS, CKA, CKAD, LFCE e LFCS (credly.com/users/thyarles). Trabalho, ainda, há 
    quatro anos no time de inovação onde utilizamos Hadoop (Cloudera) e modelos open source para treinarmos LLMs privados, 
    com GPUs em cluster, para o Smartlab (smartlab.mpt.mp.br). De outubro de 2021 a junho de 2023 eu trabalhei para uma 
    empresa internacional, VTEX, com sede em Nova York, liderando o time de engenharia de qualidade todas as comunicações 
    eram em inglês e tudo funcionou muito bem (linkedin.com/in/thyarles). A minha trajetória na computação tem sido marcada 
    por paixão e dedicação incessantes. No Ensino Médio, aos 15 anos, tive meu primeiro contato com um PC XT: 
    em dois dias dominei o WordStar incluindo o malabarismo que tínhamos que fazer para acentuar as letras , 
    o Lotus 1-2-3 e o MS-DOS 3.1; logo fui escalado para auxiliar o professor nas aulas de informática. 
    De uma forma heróica, mesmo diante de tantas dificuldades financeiras, minha mãe me presenteou com um PC XT 
    Turbo 10 MHz usado que vimos no jornal, financiado em parcelas a perder de vista. Prometi que não a decepcionaria 
    e pagaria tudo de volta, assim o fiz. Aprendi a programar em Basic e, aos 16 anos, já sabia todos os comandos do MS-DOS 
    e criava jogos. Aos 17 anos consegui uma das duas vagas de estágio na Caixa Econômica Federal, onde concorri com mais 
    de cem estudantes: embora nunca tivesse usado o Windows 95, Word e Excel até aquele momento, de alguma forma eu sabia 
    o que fazer e fiquei em primeiro lugar. Repeti o feito ao superar cerca de trinta candidatos para uma vaga de diagramador 
    no Leonardo da Vinci ao obter a melhor nota em CorelDraw e PhotoPaint, softwares que até então eu nem sabia da existência; 
    preenchi a única vaga disponível e, mais ou menos um ano depois, promoveram-me chefe do setor. Durante a minha jornada 
    profissional trabalhei com muitas tecnologias, sendo algumas complexas geoprocessamento (ArcGIS) e infraestrutura de 
    Plone/Zope e outras commodities: storage (DAS, NAS, SAN), redes (BIND, DHCP, Apache, NGINX, Squid, Varnish, iptables), 
    servidores (Linux, Windows) e virtualizadores (Xen e VMWare). Em toda minha caminhada sempre valorizei a pesquisa acadêmica, 
    pois é uma forma ímpar não somente para incrementar os meus conhecimentos com metodologia de qualidade e professores 
    experientes, mas também para eu devolver um pouco para a sociedade tudo aquilo que o ensino público me proporcionou por 
    exemplo, o meu projeto de graduação foi a criação de uma impressora braile de baixo custo (concluído com sucesso). 
    Por fim, ando de mão dada com a segurança da informação e automação; estudo diariamente como os hackers atuam, as 
    vulnerabilidades que exploram e como automatizar o máximo possível das minhas tarefas diárias não somente como forma de 
    aperfeiçoar a segurança dos sistemas, mas também para observar a Lei Geral de Proteção de Dados Pessoais (LGPD) e manter 
    os dados dos nossos usuários seguros.
  Terminal:
    userName: charles.santos
    pcName: t7
    workDir: me
    profile: whoami.txt
    description: |
      - Bachelor's in Computer Engineering
      - Degree in Statistics suspended (50%)
      - Master's in Mechatronics Engineering
      - PhD student in IT
      - Extensive experience in technology
      - Work is a paid hobby for me
  Tree_01:
    use: true
    folderName:
      skills
    files:
      - - DevOps
        - https://www.credly.com/users/thyarles/badges
      - - CKS
        - https://www.credly.com/badges/3af4a40a-4ea7-43b3-ba48-2de1849f27f3
      - - CKA
        - https://www.credly.com/badges/9dd468c6-4baf-4c56-88c5-a4a2b61efbbb
      - - CKAD
        - https://www.credly.com/badges/b7a8c8bd-92ad-4944-bbb2-bf07cf417a3e
      - - LFCE
        - https://www.credly.com/badges/32ac2769-4cb6-47aa-a1e5-6ac923101e22
      - - LFCS
        - https://www.credly.com/badges/9ce3809f-b641-48ca-8b5f-23006664dd67
      - - GitHub
        - https://github.com/thyarles
      - - Linkedin
        - https://www.linkedin.com/in/thyarles/
      - - Smartlab
        - https://smartlabbr.org
      - - Hacking
        - https://oab-ma.jusbrasil.com.br/noticias/1994233/tse-seleciona-32-hackers-para-testa-urnas-eletronicas
  Tree_02:
    use: true
    folderName:
      publications
    files:
      - - Low cost Braille printer, 2008 
        - https://www.provadigital.com.br/docs/braille.pdf
      - - Proposal for NCM, 2011
        - https://www.provadigital.com.br/docs/ncm.pdf
