baseURL: https://www.provadigital.com.br/
languageCode: en-us
title: Charles Santos
theme: bash

Params:
  description: |
    Charles Henrique Gonçalves Santos has a degree in Computer Engineering, 
    a master's degree in Mechatronic Systems, and is a PhD student in Computer 
    Science at UnB. I currently work as an Infrastructure Analyst at the Public 
    Ministry of Labor, leading the DevOps team with excellence in Linux and Kubernetes, 
    with professional certifications CKS, CKA, CKAD, LFCE, and LFCS. I have been part 
    of the innovation team for four years, where we use Hadoop (Cloudera) and open source 
    models to train private LLMs, with clustered GPUs, for smartlabbr.org. From October 2021 
    to June 2023, I worked for an international company, VTEX, headquartered in New York, 
    leading the quality engineering team.
  Terminal:
    userName: charles.santos
    pcName: t7
    workDir: me
    profile: whoami.txt
    description: |
      - Bachelor's in Computer Engineering
      - Degree in Statistics suspended (50%)
      - Master's in Mechatronics Engineering
      - PhD student in Informatics at UnB
      - Extensive experience in technology
      - Work is a paid hobby for me
  Tree_01:
    use: true
    folderName:
      skills
    files:
      - - DevOps
        - https://www.credly.com/users/thyarles/badges
      - - CKS
        - https://www.credly.com/badges/3af4a40a-4ea7-43b3-ba48-2de1849f27f3
      - - CKA
        - https://www.credly.com/badges/9dd468c6-4baf-4c56-88c5-a4a2b61efbbb
      - - CKAD
        - https://www.credly.com/badges/b7a8c8bd-92ad-4944-bbb2-bf07cf417a3e
      - - LFCE
        - https://www.credly.com/badges/32ac2769-4cb6-47aa-a1e5-6ac923101e22
      - - LFCS
        - https://www.credly.com/badges/9ce3809f-b641-48ca-8b5f-23006664dd67
      - - GitHub
        - https://github.com/thyarles
      - - Linkedin
        - https://www.linkedin.com/in/thyarles/
      - - Smartlab
        - https://smartlabbr.org
      - - Hacking
        - https://oab-ma.jusbrasil.com.br/noticias/1994233/tse-seleciona-32-hackers-para-testa-urnas-eletronicas
  Tree_02:
    use: true
    folderName:
      publications
    files:
      - - Low cost Braille printer, 2008 
        - https://www.provadigital.com.br/docs/braille.pdf
      - - Proposal for NCM, 2011
        - https://www.provadigital.com.br/docs/ncm.pdf
